Remove unready factory jobs and fix options interfaces

diff --git a/.factory/automation.yml b/.factory/automation.yml
--- a/.factory/automation.yml
+++ b/.factory/automation.yml
@@ -68,29 +68,30 @@ build:
 #        git diff --exit-code dependencies/maven/artifacts.snapshot
 #        bazel run @typedb_dependencies//tool/unuseddeps:unused-deps -- list
 
-    build-docs:
-      image: typedb-ubuntu-22.04
-      command: |
-        curl -L https://github.com/doxygen/doxygen/releases/download/Release_1_10_0/doxygen-1.10.0.linux.bin.tar.gz | tar xzO doxygen-1.10.0/bin/doxygen > /var/tmp/doxygen &&
-          sudo mv /var/tmp/doxygen /usr/local/bin/ && sudo chmod +x /usr/local/bin/doxygen
-        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
-        
-        # TODO: Temporarily update only 3.0 drivers
-        DOCS_DIRS=("docs/modules/ROOT/partials/rust" "docs/modules/ROOT/partials/java" "docs/modules/ROOT/partials/python" "docs/modules/ROOT/partials/http-ts")
-        find "${DOCS_DIRS[@]}" -type f ! -name 'api-reference.adoc' -exec rm -f {} \;
-        tool/docs/update.sh
-        git add "${DOCS_DIRS[@]}"
-        git diff --exit-code HEAD "${DOCS_DIRS[@]}" || { 
-          echo "Failed to verify docs files: please update it manually and verify the changes"
-          exit 1
-        }
-        
-        tool/docs/update_readme.sh
-        git add .
-        git diff --exit-code || {
-          echo "Failed to verify README files: please update it manually and verify the changes"
-          exit 1
-        }
+# TODO: Uncomment when we're ready to expose this in Cluster
+#    build-docs:
+#      image: typedb-ubuntu-22.04
+#      command: |
+#        curl -L https://github.com/doxygen/doxygen/releases/download/Release_1_10_0/doxygen-1.10.0.linux.bin.tar.gz | tar xzO doxygen-1.10.0/bin/doxygen > /var/tmp/doxygen &&
+#          sudo mv /var/tmp/doxygen /usr/local/bin/ && sudo chmod +x /usr/local/bin/doxygen
+#        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
+#
+#        # TODO: Temporarily update only 3.0 drivers
+#        DOCS_DIRS=("docs/modules/ROOT/partials/rust" "docs/modules/ROOT/partials/java" "docs/modules/ROOT/partials/python" "docs/modules/ROOT/partials/http-ts")
+#        find "${DOCS_DIRS[@]}" -type f ! -name 'api-reference.adoc' -exec rm -f {} \;
+#        tool/docs/update.sh
+#        git add "${DOCS_DIRS[@]}"
+#        git diff --exit-code HEAD "${DOCS_DIRS[@]}" || {
+#          echo "Failed to verify docs files: please update it manually and verify the changes"
+#          exit 1
+#        }
+#
+#        tool/docs/update_readme.sh
+#        git add .
+#        git diff --exit-code || {
+#          echo "Failed to verify README files: please update it manually and verify the changes"
+#          exit 1
+#        }
 
     test-rust-unit-integration:
       image: typedb-ubuntu-20.04 # Ubuntu 20.04 has GLIBC version 2.31 (2020) which we should verify to compile against
@@ -161,120 +162,121 @@ build:
         tool/test/stop-community-server.sh
         exit $TEST_SUCCESS
 
-    test-java-integration:
-      image: typedb-ubuntu-22.04
-      command: |
-        export ARTIFACT_USERNAME=$REPO_TYPEDB_USERNAME
-        export ARTIFACT_PASSWORD=$REPO_TYPEDB_PASSWORD
-        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
-        bazel run @typedb_dependencies//distribution/artifact:create-netrc
-        
-        tool/test/start-community-server.sh &&
-          bazel test //java/test/integration:all --test_output=streamed --jobs=1 &&
-          export COMMUNITY_FAILED= || export COMMUNITY_FAILED=1
-        tool/test/stop-community-server.sh
-        if [[ -n "$COMMUNITY_FAILED" ]]; then exit 1; fi
-
-        # TODO: Use cluster server artifact with 3 nodes for the same common tests when available
-        # source tool/test/start-cluster-servers.sh 3 &&
-        #   bazel test //java/test/integration:all --test_output=streamed --jobs=1 &&
-        #   export CLUSTER_FAILED= || export CLUSTER_FAILED=1
-        # tool/test/stop-cluster-servers.sh
-        # if [[ -n "CLUSTER_FAILED" ]]; then exit 1; fi
-
-    test-java-behaviour-community:
-      image: typedb-ubuntu-22.04
-      command: |
-        export ARTIFACT_USERNAME=$REPO_TYPEDB_USERNAME
-        export ARTIFACT_PASSWORD=$REPO_TYPEDB_PASSWORD
-        bazel run @typedb_dependencies//distribution/artifact:create-netrc
-        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
-        
-        tool/test/start-community-server.sh &&
-          .factory/test-community.sh //java/test/behaviour/... --test_output=streamed --jobs=1 &&
-          export TEST_SUCCESS=0 || export TEST_SUCCESS=1
-        tool/test/stop-community-server.sh
-        exit $TEST_SUCCESS
-
-    test-java-behaviour-cluster:
-      image: typedb-ubuntu-22.04
-      command: |
-        export ARTIFACT_USERNAME=$REPO_TYPEDB_USERNAME
-        export ARTIFACT_PASSWORD=$REPO_TYPEDB_PASSWORD
-        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
-        bazel run @typedb_dependencies//distribution/artifact:create-netrc
-        
-        
-        # TODO: run `.factory/test-cluster.sh //java/test/behaviour/...` instead of multiple tests (cannot do Clustered migration now)
-        source tool/test/start-cluster-servers.sh 3 &&
-          .factory/test-cluster.sh //java/test/behaviour/connection/... --test_env=ROOT_CA=$ROOT_CA --test_output=streamed --jobs=1 &&
-          .factory/test-cluster.sh //java/test/behaviour/driver/concept/... --test_env=ROOT_CA=$ROOT_CA --test_output=streamed --jobs=1 &&
-          .factory/test-cluster.sh //java/test/behaviour/driver/connection/... --test_env=ROOT_CA=$ROOT_CA --test_output=streamed --jobs=1 &&
-          .factory/test-cluster.sh //java/test/behaviour/driver/query/... --test_env=ROOT_CA=$ROOT_CA --test_output=streamed --jobs=1 &&
-          .factory/test-cluster.sh //java/test/behaviour/driver/user/... --test_env=ROOT_CA=$ROOT_CA --test_output=streamed --jobs=1 &&
-          export TEST_SUCCESS=0 || export TEST_SUCCESS=1
-        tool/test/stop-cluster-servers.sh
-        exit $TEST_SUCCESS
-
-    test-python-integration:
-      image: typedb-ubuntu-22.04
-      type: foreground
-      command: |
-        export PATH="$HOME/.local/bin:$PATH"
-        export ARTIFACT_USERNAME=$REPO_TYPEDB_USERNAME
-        export ARTIFACT_PASSWORD=$REPO_TYPEDB_PASSWORD
-        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
-        bazel run @typedb_dependencies//distribution/artifact:create-netrc
-
-        tool/test/start-community-server.sh &&
-          bazel test //python/tests/integration:all --test_output=streamed --jobs=1 &&
-          export COMMUNITY_FAILED= || export COMMUNITY_FAILED=1
-        tool/test/stop-community-server.sh
-        if [[ -n "$COMMUNITY_FAILED" ]]; then exit 1; fi
-
-        # TODO: Use cluster server artifact with 3 nodes when available
-        # source tool/test/start-cluster-servers.sh 3 &&
-        #   bazel test //python/tests/integration:all --test_output=streamed --jobs=1 &&
-        #   export CLUSTER_FAILED= || export CLUSTER_FAILED=1
-        # tool/test/stop-cluster-servers.sh
-        # if [[ -n "$CLUSTER_FAILED" ]]; then exit 1; fi
-
-    test-python-behaviour-community:
-      image: typedb-ubuntu-22.04
-      type: foreground
-      command: |
-        export PATH="$HOME/.local/bin:$PATH"
-        export ARTIFACT_USERNAME=$REPO_TYPEDB_USERNAME
-        export ARTIFACT_PASSWORD=$REPO_TYPEDB_PASSWORD
-        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
-        bazel run @typedb_dependencies//distribution/artifact:create-netrc
-
-        tool/test/start-community-server.sh &&
-          .factory/test-community.sh //python/tests/behaviour/... --test_output=streamed --jobs=1 &&
-          export TEST_SUCCESS=0 || export TEST_SUCCESS=1
-        tool/test/stop-community-server.sh
-        exit $TEST_SUCCESS
-
-    test-python-behaviour-cluster:
-      image: typedb-ubuntu-22.04
-      type: foreground
-      command: |
-        export PATH="$HOME/.local/bin:$PATH"
-        export ARTIFACT_USERNAME=$REPO_TYPEDB_USERNAME
-        export ARTIFACT_PASSWORD=$REPO_TYPEDB_PASSWORD
-        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
-        bazel run @typedb_dependencies//distribution/artifact:create-netrc
-        
-        # TODO: run `.factory/test-cluster.sh //python/tests/behaviour/...` instead of multiple tests (cannot do Clustered migration now)
-        source tool/test/start-cluster-servers.sh 3 &&
-          .factory/test-cluster.sh //python/tests/behaviour/connection/... --test_env=ROOT_CA=$ROOT_CA --test_output=streamed --jobs=1 &&
-          .factory/test-cluster.sh //python/tests/behaviour/driver/concept/... --test_env=ROOT_CA=$ROOT_CA --test_output=streamed --jobs=1 &&
-          .factory/test-cluster.sh //python/tests/behaviour/driver/connection/... --test_env=ROOT_CA=$ROOT_CA --test_output=streamed --jobs=1 &&
-          .factory/test-cluster.sh //python/tests/behaviour/driver/query/... --test_env=ROOT_CA=$ROOT_CA --test_output=streamed --jobs=1 &&
-          .factory/test-cluster.sh //python/tests/behaviour/driver/user/... --test_env=ROOT_CA=$ROOT_CA --test_output=streamed --jobs=1 &&
-          export TEST_SUCCESS=0 || export TEST_SUCCESS=1
-        tool/test/stop-cluster-servers.sh
-        exit $TEST_SUCCESS
+# TODO: Uncomment when java and python are ready
+#    test-java-integration:
+#      image: typedb-ubuntu-22.04
+#      command: |
+#        export ARTIFACT_USERNAME=$REPO_TYPEDB_USERNAME
+#        export ARTIFACT_PASSWORD=$REPO_TYPEDB_PASSWORD
+#        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
+#        bazel run @typedb_dependencies//distribution/artifact:create-netrc
+#
+#        tool/test/start-community-server.sh &&
+#          bazel test //java/test/integration:all --test_output=streamed --jobs=1 &&
+#          export COMMUNITY_FAILED= || export COMMUNITY_FAILED=1
+#        tool/test/stop-community-server.sh
+#        if [[ -n "$COMMUNITY_FAILED" ]]; then exit 1; fi
+#
+#        # TODO: Use cluster server artifact with 3 nodes for the same common tests when available
+#        # source tool/test/start-cluster-servers.sh 3 &&
+#        #   bazel test //java/test/integration:all --test_output=streamed --jobs=1 &&
+#        #   export CLUSTER_FAILED= || export CLUSTER_FAILED=1
+#        # tool/test/stop-cluster-servers.sh
+#        # if [[ -n "CLUSTER_FAILED" ]]; then exit 1; fi
+#
+#    test-java-behaviour-community:
+#      image: typedb-ubuntu-22.04
+#      command: |
+#        export ARTIFACT_USERNAME=$REPO_TYPEDB_USERNAME
+#        export ARTIFACT_PASSWORD=$REPO_TYPEDB_PASSWORD
+#        bazel run @typedb_dependencies//distribution/artifact:create-netrc
+#        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
+#
+#        tool/test/start-community-server.sh &&
+#          .factory/test-community.sh //java/test/behaviour/... --test_output=streamed --jobs=1 &&
+#          export TEST_SUCCESS=0 || export TEST_SUCCESS=1
+#        tool/test/stop-community-server.sh
+#        exit $TEST_SUCCESS
+#
+#    test-java-behaviour-cluster:
+#      image: typedb-ubuntu-22.04
+#      command: |
+#        export ARTIFACT_USERNAME=$REPO_TYPEDB_USERNAME
+#        export ARTIFACT_PASSWORD=$REPO_TYPEDB_PASSWORD
+#        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
+#        bazel run @typedb_dependencies//distribution/artifact:create-netrc
+#
+#
+#        # TODO: run `.factory/test-cluster.sh //java/test/behaviour/...` instead of multiple tests (cannot do Clustered migration now)
+#        source tool/test/start-cluster-servers.sh 3 &&
+#          .factory/test-cluster.sh //java/test/behaviour/connection/... --test_env=ROOT_CA=$ROOT_CA --test_output=streamed --jobs=1 &&
+#          .factory/test-cluster.sh //java/test/behaviour/driver/concept/... --test_env=ROOT_CA=$ROOT_CA --test_output=streamed --jobs=1 &&
+#          .factory/test-cluster.sh //java/test/behaviour/driver/connection/... --test_env=ROOT_CA=$ROOT_CA --test_output=streamed --jobs=1 &&
+#          .factory/test-cluster.sh //java/test/behaviour/driver/query/... --test_env=ROOT_CA=$ROOT_CA --test_output=streamed --jobs=1 &&
+#          .factory/test-cluster.sh //java/test/behaviour/driver/user/... --test_env=ROOT_CA=$ROOT_CA --test_output=streamed --jobs=1 &&
+#          export TEST_SUCCESS=0 || export TEST_SUCCESS=1
+#        tool/test/stop-cluster-servers.sh
+#        exit $TEST_SUCCESS
+#
+#    test-python-integration:
+#      image: typedb-ubuntu-22.04
+#      type: foreground
+#      command: |
+#        export PATH="$HOME/.local/bin:$PATH"
+#        export ARTIFACT_USERNAME=$REPO_TYPEDB_USERNAME
+#        export ARTIFACT_PASSWORD=$REPO_TYPEDB_PASSWORD
+#        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
+#        bazel run @typedb_dependencies//distribution/artifact:create-netrc
+#
+#        tool/test/start-community-server.sh &&
+#          bazel test //python/tests/integration:all --test_output=streamed --jobs=1 &&
+#          export COMMUNITY_FAILED= || export COMMUNITY_FAILED=1
+#        tool/test/stop-community-server.sh
+#        if [[ -n "$COMMUNITY_FAILED" ]]; then exit 1; fi
+#
+#        # TODO: Use cluster server artifact with 3 nodes when available
+#        # source tool/test/start-cluster-servers.sh 3 &&
+#        #   bazel test //python/tests/integration:all --test_output=streamed --jobs=1 &&
+#        #   export CLUSTER_FAILED= || export CLUSTER_FAILED=1
+#        # tool/test/stop-cluster-servers.sh
+#        # if [[ -n "$CLUSTER_FAILED" ]]; then exit 1; fi
+#
+#    test-python-behaviour-community:
+#      image: typedb-ubuntu-22.04
+#      type: foreground
+#      command: |
+#        export PATH="$HOME/.local/bin:$PATH"
+#        export ARTIFACT_USERNAME=$REPO_TYPEDB_USERNAME
+#        export ARTIFACT_PASSWORD=$REPO_TYPEDB_PASSWORD
+#        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
+#        bazel run @typedb_dependencies//distribution/artifact:create-netrc
+#
+#        tool/test/start-community-server.sh &&
+#          .factory/test-community.sh //python/tests/behaviour/... --test_output=streamed --jobs=1 &&
+#          export TEST_SUCCESS=0 || export TEST_SUCCESS=1
+#        tool/test/stop-community-server.sh
+#        exit $TEST_SUCCESS
+#
+#    test-python-behaviour-cluster:
+#      image: typedb-ubuntu-22.04
+#      type: foreground
+#      command: |
+#        export PATH="$HOME/.local/bin:$PATH"
+#        export ARTIFACT_USERNAME=$REPO_TYPEDB_USERNAME
+#        export ARTIFACT_PASSWORD=$REPO_TYPEDB_PASSWORD
+#        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
+#        bazel run @typedb_dependencies//distribution/artifact:create-netrc
+#
+#        # TODO: run `.factory/test-cluster.sh //python/tests/behaviour/...` instead of multiple tests (cannot do Clustered migration now)
+#        source tool/test/start-cluster-servers.sh 3 &&
+#          .factory/test-cluster.sh //python/tests/behaviour/connection/... --test_env=ROOT_CA=$ROOT_CA --test_output=streamed --jobs=1 &&
+#          .factory/test-cluster.sh //python/tests/behaviour/driver/concept/... --test_env=ROOT_CA=$ROOT_CA --test_output=streamed --jobs=1 &&
+#          .factory/test-cluster.sh //python/tests/behaviour/driver/connection/... --test_env=ROOT_CA=$ROOT_CA --test_output=streamed --jobs=1 &&
+#          .factory/test-cluster.sh //python/tests/behaviour/driver/query/... --test_env=ROOT_CA=$ROOT_CA --test_output=streamed --jobs=1 &&
+#          .factory/test-cluster.sh //python/tests/behaviour/driver/user/... --test_env=ROOT_CA=$ROOT_CA --test_output=streamed --jobs=1 &&
+#          export TEST_SUCCESS=0 || export TEST_SUCCESS=1
+#        tool/test/stop-cluster-servers.sh
+#        exit $TEST_SUCCESS
 
     test-http-ts-behaviour-community:
       image: typedb-ubuntu-22.04
