Add TypeDB Cluster support and failover (#765)
Introduce TypeDB Cluster support. Including:

Drivers can be created using a single address, multiple addresses, or
address translation (mapping between public user-facing addresses and
internal cluster addresses for special needs). Address translation can
be updated after the driver is created.

Server version and distribution, as well as the list of active replicas,
can be retrieved using TypeDB Driver.

Read operations can be executed using one of three strategies:
* Strong consistency level -- Strongest consistency, always up-to-date
due to the guarantee of the primary replica usage.
* Eventual consistency level -- Allow stale reads from any replica. May
not reflect latest writes (will not be supported in the first Cluster
release on the server side, so will probably return errors)
* Replica dependent consistency level -- The operation is executed
against the provided replica address only. Can be especially useful for
testing.

By default, all operations are executed using the strongest consistency
level. However, all read operations now support consistency level
specification. Read transactions can be configured through transaction
options.

Driver options can be used to configure the failover strategies used
with strong and eventual consistency levels.

`primary_failover_retries` -- Limits the number of attempts to redirect
a strongly consistent request to another primary replica in case of a
failure due to the change of replica roles. Defaults to 1.
`replica_discovery_attempts` -- Limits the number of driver attempts to
discover a single working replica to perform an operation in case of a
replica unavailability. Every replica is tested once, which means that
at most:
- {limit} operations are performed if the limit <= the number of
replicas.
- {number of replicas} operations are performed if the limit > the
number of replicas.
- {number of replicas} operations are performed if the limit is None.
Affects every eventually consistent operation, including redirect
failover, when the new primary replica is unknown. Defaults to None.

**Missing parts**:
* Address translation runtime update is not fully implemented, it
probably requires more updates, or can be removed for the first release.
* Testing cannot be automated without Cluster snapshots. Instead, for
local testing, use `temp-cluster-server` (instructions below).
* The driver works itself, the tests for Core pass. However, its
replication features are untested. There is a new `clustering`
integration test, which successfully boots up servers, but there are
some missing functionalities of the server that prevent the testing
progress. Once the PR referenced below is completed and merged, it can
be completed, as well. More BDD tests should be added here
https://github.com/typedb/typedb-behaviour/pull/373

This driver can be tested using the server from
https://github.com/typedb/typedb-cluster/pull/608. To do so, run `cargo
build` in `typedb-cluster`, and then copy the resulting binary to
`typedb-driver` like:
```
cp path-to-typedb/typedb-cluster/target/debug/typedb_server_bin path-to-typedb/typedb-driver/tool/test/temp-cluster-server/typedb
```
Then, test scripts like
`./tool/test/temp-cluster-server/start-cluster-servers.sh 3` can be
used.
Note that it is a temporary directory, created to use the server while
we are not able to use Cluster snapshots from Bazel.

diff --git a/.factory/automation.yml b/.factory/automation.yml
--- a/.factory/automation.yml
+++ b/.factory/automation.yml
@@ -50,10 +50,10 @@ build:
         bazel run @typedb_dependencies//distribution/artifact:create-netrc
         # TODO: Temporarily build only the 3.0-reimplemented drivers:
         # bazel build //...
-        bazel build //c/...
+        # bazel build //c/...
         bazel build //rust/...
-        bazel build //java/...
-        bazel build //python/...
+        # bazel build //java/...
+        # bazel build //python/...
         bazel build //http-ts/...
         
         bazel run @typedb_dependencies//tool/checkstyle:test-coverage
@@ -87,8 +87,8 @@ build:
         
         tool/docs/update_readme.sh
         git add .
-        git diff --exit-code || { 
-          echo "Failed to verify README files: plese update it manually and verify the changes"
+        git diff --exit-code || {
+          echo "Failed to verify README files: please update it manually and verify the changes"
           exit 1
         }
 
@@ -109,7 +109,7 @@ build:
         if [[ -n "$COMMUNITY_FAILED" ]]; then exit 1; fi
         
         # TODO: Use cluster server artifact with 3 nodes for the same common tests when available
-        # tool/test/start-cluster-servers.sh 3 &&
+        # source tool/test/start-cluster-servers.sh 3 &&
         #   bazel test //rust/tests/integration:all --test_output=streamed --test_arg=--nocapture &&
         #   export CLUSTER_FAILED= || export CLUSTER_FAILED=1
         # tool/test/stop-cluster-servers.sh
@@ -129,22 +129,21 @@ build:
         tool/test/stop-community-server.sh
         exit $TEST_SUCCESS
 
-    # TODO: Use cluster server artifact with 3 nodes when available (it would do the same thing as community now)
-    # test-rust-behaviour-cluster:
-    #   image: typedb-ubuntu-20.04 # Ubuntu 20.04 has GLIBC version 2.31 (2020) which we should verify to compile against
-    #   dependencies:
-    #     - build
-    #   command: |
-    #     export ARTIFACT_USERNAME=$REPO_TYPEDB_USERNAME
-    #     export ARTIFACT_PASSWORD=$REPO_TYPEDB_PASSWORD
-    #     bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
-    #     bazel run @typedb_dependencies//distribution/artifact:create-netrc
-    #
-    #     tool/test/start-cluster-servers.sh 3 &&
-    #       bazel test //rust/tests/behaviour/...  --//rust/tests/behaviour/config:mode=cluster --test_output=streamed --jobs=1 &&
-    #       export TEST_SUCCESS=0 || export TEST_SUCCESS=1
-    #     tool/test/stop-cluster-servers.sh
-    #     exit $TEST_SUCCESS
+    test-rust-behaviour-cluster:
+      image: typedb-ubuntu-20.04 # Ubuntu 20.04 has GLIBC version 2.31 (2020) which we should verify to compile against
+      dependencies:
+        - build
+      command: |
+        export ARTIFACT_USERNAME=$REPO_TYPEDB_USERNAME
+        export ARTIFACT_PASSWORD=$REPO_TYPEDB_PASSWORD
+        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
+        bazel run @typedb_dependencies//distribution/artifact:create-netrc
+ 
+        source tool/test/start-cluster-servers.sh 3 &&
+          bazel test //rust/tests/behaviour/... --test_env=ROOT_CA=$ROOT_CA --//rust/tests/behaviour/config:mode=cluster --test_output=streamed --jobs=1 &&
+          export TEST_SUCCESS=0 || export TEST_SUCCESS=1
+        tool/test/stop-cluster-servers.sh
+        exit $TEST_SUCCESS
 
     test-c-integration:
       image: typedb-ubuntu-20.04 # Ubuntu 20.04 has GLIBC version 2.31 (2020) which we should verify to compile against
@@ -176,7 +175,7 @@ build:
         if [[ -n "$COMMUNITY_FAILED" ]]; then exit 1; fi
 
         # TODO: Use cluster server artifact with 3 nodes for the same common tests when available
-        # tool/test/start-cluster-servers.sh 3 &&
+        # source tool/test/start-cluster-servers.sh 3 &&
         #   bazel test //java/test/integration:all --test_output=streamed --jobs=1 &&
         #   export CLUSTER_FAILED= || export CLUSTER_FAILED=1
         # tool/test/stop-cluster-servers.sh
@@ -196,22 +195,21 @@ build:
         tool/test/stop-community-server.sh
         exit $TEST_SUCCESS
 
-    # TODO: Use cluster server artifact with 3 nodes when available (it would do the same thing as community now)
-    # test-java-behaviour-cluster:
-    #   image: typedb-ubuntu-22.04
-    #   dependencies:
-    #     - build
-    #   command: |
-    #     export ARTIFACT_USERNAME=$REPO_TYPEDB_USERNAME
-    #     export ARTIFACT_PASSWORD=$REPO_TYPEDB_PASSWORD
-    #     bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
-    #     bazel run @typedb_dependencies//distribution/artifact:create-netrc
-    #
-    #     tool/test/start-cluster-servers.sh 3 &&
-    #       .factory/test-cluster.sh //java/test/behaviour/... --test_output=streamed --jobs=1 &&
-    #       export TEST_SUCCESS=0 || export TEST_SUCCESS=1
-    #     tool/test/stop-cluster-servers.sh
-    #     exit $TEST_SUCCESS
+    test-java-behaviour-cluster:
+      image: typedb-ubuntu-22.04
+      dependencies:
+        - build
+      command: |
+        export ARTIFACT_USERNAME=$REPO_TYPEDB_USERNAME
+        export ARTIFACT_PASSWORD=$REPO_TYPEDB_PASSWORD
+        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
+        bazel run @typedb_dependencies//distribution/artifact:create-netrc
+        
+        source tool/test/start-cluster-servers.sh 3 &&
+          .factory/test-cluster.sh //java/test/behaviour/... --test_env=ROOT_CA=$ROOT_CA --test_output=streamed --jobs=1 &&
+          export TEST_SUCCESS=0 || export TEST_SUCCESS=1
+        tool/test/stop-cluster-servers.sh
+        exit $TEST_SUCCESS
 
     test-python-integration:
       image: typedb-ubuntu-22.04
@@ -230,7 +228,7 @@ build:
         if [[ -n "$COMMUNITY_FAILED" ]]; then exit 1; fi
 
         # TODO: Use cluster server artifact with 3 nodes when available
-        # tool/test/start-cluster-servers.sh 3 &&
+        # source tool/test/start-cluster-servers.sh 3 &&
         #   bazel test //python/tests/integration:all --test_output=streamed --jobs=1 &&
         #   export CLUSTER_FAILED= || export CLUSTER_FAILED=1
         # tool/test/stop-cluster-servers.sh
@@ -252,24 +250,23 @@ build:
         tool/test/stop-community-server.sh
         exit $TEST_SUCCESS
 
-    # TODO: Use cluster server artifact with 3 nodes when available (it would do the same thing as community now)
-    # test-python-behaviour-cluster:
-    #   image: typedb-ubuntu-22.04
-    #   dependencies:
-    #     - build
-    #   type: foreground
-    #   command: |
-    #     export PATH="$HOME/.local/bin:$PATH"
-    #     export ARTIFACT_USERNAME=$REPO_TYPEDB_USERNAME
-    #     export ARTIFACT_PASSWORD=$REPO_TYPEDB_PASSWORD
-    #     bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
-    #     bazel run @typedb_dependencies//distribution/artifact:create-netrc
-    #
-    #     tool/test/start-cluster-servers.sh 3 &&
-    #       .factory/test-cluster.sh //python/tests/behaviour/... --test_output=streamed --jobs=1 &&
-    #       export TEST_SUCCESS=0 || export TEST_SUCCESS=1
-    #     tool/test/stop-cluster-servers.sh
-    #     exit $TEST_SUCCESS
+    test-python-behaviour-cluster:
+      image: typedb-ubuntu-22.04
+      dependencies:
+        - build
+      type: foreground
+      command: |
+        export PATH="$HOME/.local/bin:$PATH"
+        export ARTIFACT_USERNAME=$REPO_TYPEDB_USERNAME
+        export ARTIFACT_PASSWORD=$REPO_TYPEDB_PASSWORD
+        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
+        bazel run @typedb_dependencies//distribution/artifact:create-netrc
+        
+        source tool/test/start-cluster-servers.sh 3 &&
+          .factory/test-cluster.sh //python/tests/behaviour/... --test_env=ROOT_CA=$ROOT_CA --test_output=streamed --jobs=1 &&
+          export TEST_SUCCESS=0 || export TEST_SUCCESS=1
+        tool/test/stop-cluster-servers.sh
+        exit $TEST_SUCCESS
 
 
     test-http-ts-behaviour-community:
